[package]
name = "byte-utils"
version = "0.1.0"
license = "MIT"
description = "A collection of utilities for byte manipulation and conversion."
keywords = ["encoding", "decoding", "conversion", "ULEB128", "SLEB128"]
repository = "https://github.com/NatLabs/ByteUtils"

[dependencies]
base = "0.14.11"
xtended-numbers = "0.4.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "1.0.0"
augmented-btrees = "0.6.0"
itertools = "0.2.2"

[toolchain]
moc = "0.14.9"
wasmtime = "28.0.1"
