[dependencies]
base = "0.10.2"
xtended-numbers = "0.4.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "0.1.0"
augmented-btrees = "0.6.0"
itertools = "0.2.2"

[toolchain]
moc = "0.14.9"
wasmtime = "28.0.1"